### ISSUE TITLE
Catalog-of-my-things-ruby-Captsone

### ISSUE THREAD

**Issue by hienphan0111** [hienphan0111/catalog-of-thing#20]
_This is the Ruby Capstone Project we are going to work with 3 members and we are assigned by:_
- Team member 1: @hienphan0111 
- Team member 2: @alicemirigo92 
- Team member 3: @chepkok3

Link to project's Kanban board : `https://github.com/hienphan0111/catalog-of-thing/projects/1`

**Comment by m05e5** [comment]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project without the link to your Kanban board. please make sure to add it to your issue description

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by m05e5** [comment]
**Hi Team
You did great. Your Kanban board is complete!  There is nothing else to say other than... it's time to start coding:shipit: 
Congratulations! 🎉 
![CleverScornfulBuffalo-size_restricted](https://user-images.githubusercontent.com/37901469/208869296-5ca9f6cc-a1b5-48fd-bd59-78fd83b35471.gif)

## Highlights


✔️ Clean kanban board

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**m05e5**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._**
